Add check method
cmpayments/iban pull request #1
Opened 2016-12-08 18:29 UTC by TFarla

2016-12-08 21:05 UTC, baspeters requested changes
Thank you for your pull request. In general the additions are welcome, although I have some remarks that need to be reviewed.

Can you update README.md as well with an example of the IBAN->check() method?

Please make sure that the PSR-2 check does not contain errors before submitting the PR. Currently the travis build fails because of this.

2016-12-08 21:05 UTC, baspeters commented on src/lib/Exception/Invalid.php
> +class Invalid extends \Exception
- This class name is too generic to be in the cmpayments\exception namespace.
- Exception classes should end in ...Exception
- Suggestion would be "IbanBaseValidationException"

2016-12-08 21:05 UTC, baspeters commented on src/lib/Exception/InvalidChecksum.php
> +class InvalidChecksum extends Invalid
- Class is too generic, suggestion "IbanInvalidChecksumException"

2016-12-08 21:05 UTC, baspeters commented on src/lib/Exception/InvalidCountry.php
> +class InvalidCountry extends Invalid
- Class is too generic, suggestion "IbanInvalidCountryException"

2016-12-08 21:05 UTC, baspeters commented on src/lib/Exception/InvalidFormat.php
> +class InvalidFormat extends Invalid
- Class is too generic, suggestion "IbanInvalidFormatException"

2016-12-08 21:05 UTC, baspeters commented on src/lib/Exception/InvalidLength.php
> +class InvalidLength extends Invalid
- Class is too generic, suggestion "IbanInvalidLengthException"

2016-12-08 21:05 UTC, baspeters commented on src/lib/IBAN.php
> -    const COUNTRY_CODE_OFFSET             = 0;
- Style change should not be present in a functional PR
- Current style does not violate PSR-2, no merit in changing
- Applicable for all style changes in this file

2016-12-08 21:05 UTC, baspeters commented on src/lib/IBAN.php
> +    public function __toString()
Nice addition!

2016-12-08 21:05 UTC, baspeters commented on tests/IBANValidateTest.php
> +    public function provideValidIban()
- PHPUnit convention is to use suffix ...Provider for data provider functions
- Suggestion is to name this method "validIbanProvider"

2016-12-08 21:05 UTC, baspeters commented on tests/IBANValidateTest.php
> +    public function provideInvalidIban()
- PHPUnit convention is to use suffix ...Provider for data provider functions
- Suggestion is to name this method "invalidIbanProvider"

2016-12-08 21:05 UTC, baspeters commented on tests/IBANValidateTest.php
> +    public function provideSanitizeIban()
- PHPUnit convention is to use suffix ...Provider for data provider functions
- Suggestion is to name this method "sanitizeIbanProvider"

2016-12-08 21:05 UTC, baspeters commented on src/lib/Exception/Invalid.php
> +}
The use of a base exception and separate exceptions for each validation error seems over-engineered. Especially since these classes are all shell classes without a single line of content.

Consider making a single IbanValidationException class that distinguishes all possible validation errors by error number. Using class constants the individual errors can be mapped to "friendly" names. Convenience functions can help setting up the correct error message and number. Example:
```
class IbanValidationException extends \Exception
{
    const ERROR_INVALID_CHECKSUM = 0;
    const ERROR_INVALID_FORMAT = 1;
    const ERROR_INVALID_COUNTRY_CODE = 3;
    ...
}

throw new InvalidIbanException("IBAN Checksum failed", IbanValidationException::ERROR_INVALID_CHECKSUM)
```

2016-12-08 21:05 UTC, baspeters commented on src/lib/Exception/Invalid.php
> +namespace CMPayments\Exception;
Exceptions for this package should be namespaced into "cmpayments\iban\exceptions" to avoid namespace clashes with possible other cmpayments packages

2018-02-19 14:51 UTC, jorygeerts commented
@TFarla Do you have plans to continue work on this? If not, we can close this PR.

2018-02-27 12:42 UTC, closed without merging